spring:
  profiles:
    active: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exposed_demo
    username: user
    password: pass
    hikari:
      max-lifetime: 600000
      connectionTimeout: 5000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 30000
      leak-detection-threshold: 1200000
      test-while-idle: true
      test-on-borrow: true
  exposed:
    generate-ddl: true
    show_sql: true
  jpa:
    open-in-view: false
